### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xml_filename'

### ISSUE THREAD

**Issue by gabrieldelmondess** [viniciusrpb/dou_csv_extractor#1]
![image](https://github.com/viniciusrpb/xml2csv_diariooficialdauniao/assets/105651767/083950b2-90ac-4d31-a72d-17b4e75cdb70)

**Comment by viniciusrpb** [comment]
Olá, remova o arquivo README.md da pasta 'dou_samples' que deve funcionar.

**Comment by gabrieldelmondess** [comment]
Funcionou, professor. Obrigado.

**Comment by viniciusrpb** [comment]
Grato pelo feedback!
